### PR TITLE
add formatter and run mix format

### PR DESCRIPTION
**Pull request by yordis**

### CODE REVIEW

**Comment by yordis** [comment]
@alexdovzhanyn I can add the Travis setup but I would suggest to bumb up the version of Travis to the latest Elixir so you could take advantage of the formatter checking the errors for you.

**Comment by alexdovzhanyn** [comment]
It pains me to see all of these extra parentheses :confounded: but if its a more standard elixir approach then im alright with sacrificing my personal code style. And yeah @yordis we can bump both travis and elixir to 1.6 so long as you can verify that everything still works as expected. Thanks for the help!

**Comment by alexdovzhanyn** [comment]
@yordis let me know when you think this is ready for merge and i'll look over it once more. Looks good so far :)

**Comment by yordis** [comment]
@alexdovzhanyn it is good but this Travis will fail 😄Credo it is already complaining

**Pull request merged**
